name: lockdin-school
services:
  content-service:
    build: .
    container_name: content-service
    expose:
      - "8080"
    env_file:
      - .env.local
    networks:
      - lockdin-network
      - cont-sn
    depends_on:
      - contentDB

  contentDB:
    container_name: content-db
    image: postgres:16-alpine
    command: -p 5434
    ports:
      - "5434:5434"
    env_file:
      - .env.local
    networks:
      - cont-sn
    volumes:
      - type: volume
        source: lockdin-storage
        target: /var/lib/postgresql/content/data


volumes:
  lockdin-storage:

networks:
  cont-sn: